spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=webapp
    username: user
    password: user
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update